spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/e_commerce
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
server:
  port: 8080

springdoc:
  enable-data-rest: false
  enable-groovy: false
  enable-hateoas: false

