spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/${DB_DATABASE:e-commerce}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080

springdoc:
  enable-data-rest: false
  enable-groovy: false
  enable-hateoas: false
