spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL:localhost:3306}/${DB_DATABASE:e_commerce}
    username: ${UB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create

server:
  port: 8080

springdoc:
  enable-data-rest: false
  enable-groovy: false
  enable-hateoas: false
